import {
  aboutDegrees,
  aboutLede,
  aboutSponsorship,
  academicsIntro,
  accessibilityCopy,
  accreditationDisclaimer,
  accreditationFaq,
  aidCopy,
  alumniCopy,
  advisoryIntro,
  bachelorRequired,
  bookstoreIntro,
  calendarCopy,
  cancellationCopy,
  capstoneCopy,
  catalogUnpublished,
  careerUnpublished,
  chapelUnpublished,
  contactBlock,
  courseTexts,
  degreeMeta,
  effectivenessUnpublished,
  enrollmentLimit,
  enrollmentExpansion,
  facultyIntro,
  feesCopy,
  founderLetter,
  giveCopy,
  handbookUnpublished,
  howToApply,
  integrityUnpublished,
  legalStatus,
  libraryCopy,
  mailingListOwner,
  mailingListWhatArrives,
  macmFieldEd,
  macmOutcomes,
  macmStructure,
  macmSummary,
  maglFieldEd,
  maglOutcomes,
  maglStructure,
  maglSummary,
  mission,
  noLicensure,
  orlandoNote,
  ordinationUnpublished,
  policiesUnpublished,
  refundsCopy,
  religiousExemption,
  rollingAdmissions,
  studentSupport,
  techCopy,
  transferCopy,
  trusteesIntro,
  tuitionByCredit,
  vision,
} from "./copy";
import { people, trustees, advisory, faculty, type Person } from "./people";
import { products } from "./products";
import { pages } from "./registry";

export type AskDoc = { title: string; href: string; body: string };

function personBody(p: Person) {
  return [
    p.name,
    p.role,
    p.lede,
    ...p.education.map((e) =>
      [e.degree, e.honorary ? "honorary" : null, e.field, e.school, e.year].filter(Boolean).join(", "),
    ),
    ...(p.teaching ?? []),
    ...p.sections.flatMap((s) => [s.heading, ...s.paragraphs]),
  ].join(" ");
}

export const askCorpus: AskDoc[] = [
  { title: pages["/"].metaTitle, href: "/", body: `${aboutLede} ${orlandoNote} ${mission} ${vision}` },
  { title: "About", href: "/about", body: `${aboutLede} ${orlandoNote} ${mission} ${vision} ${aboutDegrees} ${aboutSponsorship} ${legalStatus}` },
  { title: "Mission & Vision", href: "/about/mission", body: `${mission} ${vision}` },
  { title: "Founding President", href: "/about/founder", body: personBody(people.bernard) },
  { title: "A Message from the Founding President", href: "/about/founder/message", body: founderLetter },
  { title: "Executive Vice President", href: "/about/lim", body: personBody(people.lim) },
  {
    title: "Board of Trustees",
    href: "/about/trustees",
    body: `${trusteesIntro} ${trustees.map((t) => `${t.name}, ${t.role}`).join(". ")}.`,
  },
  { title: people.weiss.name, href: "/about/trustees/weiss", body: personBody(people.weiss) },
  { title: people.halek.name, href: "/about/trustees/halek", body: personBody(people.halek) },
  {
    title: "Advisory Council",
    href: "/about/advisory",
    body: `${advisoryIntro} ${advisory.map((p) => `${p.name}, ${p.role}`).join(". ")}.`,
  },
  { title: people.jamaal.name, href: "/about/advisory/jamaal", body: personBody(people.jamaal) },
  { title: people.hernandez.name, href: "/about/advisory/hernandez", body: personBody(people.hernandez) },
  { title: people.spears.name, href: "/about/advisory/spears", body: personBody(people.spears) },
  {
    title: "Accreditation Status",
    href: "/about/accreditation",
    body: `${accreditationDisclaimer} ${religiousExemption} ${accreditationFaq.map((i) => `${i.q} ${i.a}`).join(" ")}`,
  },
  { title: "Institutional Effectiveness", href: "/about/effectiveness", body: effectivenessUnpublished },
  { title: "Academics", href: "/academics", body: academicsIntro },
  { title: "Degrees", href: "/programs", body: `${macmSummary} ${maglSummary} ${degreeMeta} ${noLicensure}` },
  {
    title: "Master of Arts in Christian Ministry",
    href: "/programs/macm",
    body: `${macmSummary} ${macmStructure} ${macmFieldEd} ${capstoneCopy} ${macmOutcomes.join(" ")} ${noLicensure}`,
  },
  {
    title: "Master of Arts in Global Christian Leadership",
    href: "/programs/magl",
    body: `${maglSummary} ${maglStructure} ${maglFieldEd} ${capstoneCopy} ${maglOutcomes.join(" ")} ${noLicensure}`,
  },
  { title: "Faculty", href: "/academics/faculty", body: `${facultyIntro} ${faculty.map((p) => personBody(p)).join(" ")}` },
  { title: people.chaparro.name, href: "/academics/faculty/chaparro", body: personBody(people.chaparro) },
  { title: people.irvin.name, href: "/academics/faculty/irvin", body: personBody(people.irvin) },
  { title: people.white.name, href: "/academics/faculty/white", body: personBody(people.white) },
  { title: "Library", href: "/academics/library", body: libraryCopy },
  { title: "Academic Catalog", href: "/academics/catalog", body: catalogUnpublished },
  { title: "Academic Policies", href: "/academics/policies", body: policiesUnpublished },
  { title: "Admissions", href: "/admissions", body: `${rollingAdmissions} ${bachelorRequired} ${enrollmentLimit} ${enrollmentExpansion}` },
  { title: "How to Apply", href: "/admissions/apply", body: howToApply },
  {
    title: "Tuition & Fees",
    href: "/tuition",
    body: `${tuitionByCredit} ${feesCopy} ${cancellationCopy} ${refundsCopy} ${aidCopy} ${accreditationDisclaimer}`,
  },
  { title: "Transfer Credit", href: "/admissions/transfer", body: transferCopy },
  { title: "Current Students", href: "/students", body: studentSupport },
  { title: "Office of Student Records and Accounts", href: "/students/records", body: `Director of Information Technology and Director of Student Records and Accounts: Randy Whittaker. studentservices@nsbt.org` },
  { title: "Student Accessibility", href: "/students/accessibility", body: accessibilityCopy },
  { title: "Technology", href: "/students/tech", body: techCopy },
  { title: "Student Handbook", href: "/students/handbook", body: handbookUnpublished },
  { title: "Career Services", href: "/students/career", body: careerUnpublished },
  { title: "Alumni", href: "/alumni", body: alumniCopy },
  { title: "Calendar", href: "/events", body: calendarCopy },
  { title: "Contact", href: "/contact", body: `${orlandoNote} ${contactBlock}` },
  { title: "Chapel", href: "/students/chapel", body: chapelUnpublished },
  { title: "Ordination", href: "/admissions/ordination", body: ordinationUnpublished },
  { title: "Academic Integrity", href: "/students/integrity", body: integrityUnpublished },
  { title: "Give", href: "/give", body: giveCopy },
  {
    title: "The NSBT Bookstore",
    href: "/store",
    body: `${bookstoreIntro} ${courseTexts} ${mailingListOwner} ${mailingListWhatArrives} ${products.map((p) => `${p.name} ${p.description}`).join(". ")}`,
  },
];
