/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteSplatRouteImport } from './routes/_site/$'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiCartRouteImport } from './routes/api/cart'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalClassRouteImport } from './routes/portal/class'
import { Route as PortalFacultyRouteImport } from './routes/portal/faculty'
import { Route as PortalHelpRouteImport } from './routes/portal/help'
import { Route as PortalLibraryRouteImport } from './routes/portal/library'
import { Route as PortalPersonRouteImport } from './routes/portal/person'
import { Route as PortalScheduleRouteImport } from './routes/portal/schedule'
import { Route as PortalStudentRouteImport } from './routes/portal/student'
import { Route as PortalWritingRouteImport } from './routes/portal/writing'
import { Route as SigninFacultyRouteImport } from './routes/signin.faculty'
import { Route as SigninStudentsRouteImport } from './routes/signin.students'
import { Route as SiteStoreHandleRouteImport } from './routes/_site/store.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSplatRoute = SiteSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SiteRoute,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartRoute = ApiCartRouteImport.update({
  id: '/api/cart',
  path: '/api/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClassRoute = PortalClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFacultyRoute = PortalFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHelpRoute = PortalHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLibraryRoute = PortalLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPersonRoute = PortalPersonRouteImport.update({
  id: '/person',
  path: '/person',
  getParentRoute: () => PortalRoute,
} as any)
const PortalScheduleRoute = PortalScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStudentRoute = PortalStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWritingRoute = PortalWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => PortalRoute,
} as any)
const SigninFacultyRoute = SigninFacultyRouteImport.update({
  id: '/signin/faculty',
  path: '/signin/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninStudentsRoute = SigninStudentsRouteImport.update({
  id: '/signin/students',
  path: '/signin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteStoreHandleRoute = SiteStoreHandleRouteImport.update({
  id: '/store/$handle',
  path: '/store/$handle',
  getParentRoute: () => SiteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/$': typeof SiteSplatRoute
  '/api/ask': typeof ApiAskRoute
  '/api/cart': typeof ApiCartRoute
  '/portal/class': typeof PortalClassRoute
  '/portal/faculty': typeof PortalFacultyRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/library': typeof PortalLibraryRoute
  '/portal/person': typeof PortalPersonRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/writing': typeof PortalWritingRoute
  '/signin/faculty': typeof SigninFacultyRoute
  '/signin/students': typeof SigninStudentsRoute
  '/portal/': typeof PortalIndexRoute
  '/store/$handle': typeof SiteStoreHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof SiteSplatRoute
  '/api/ask': typeof ApiAskRoute
  '/api/cart': typeof ApiCartRoute
  '/portal/class': typeof PortalClassRoute
  '/portal/faculty': typeof PortalFacultyRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/library': typeof PortalLibraryRoute
  '/portal/person': typeof PortalPersonRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/writing': typeof PortalWritingRoute
  '/signin/faculty': typeof SigninFacultyRoute
  '/signin/students': typeof SigninStudentsRoute
  '/': typeof SiteIndexRoute
  '/portal': typeof PortalIndexRoute
  '/store/$handle': typeof SiteStoreHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/_site/$': typeof SiteSplatRoute
  '/api/ask': typeof ApiAskRoute
  '/api/cart': typeof ApiCartRoute
  '/portal/class': typeof PortalClassRoute
  '/portal/faculty': typeof PortalFacultyRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/library': typeof PortalLibraryRoute
  '/portal/person': typeof PortalPersonRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/writing': typeof PortalWritingRoute
  '/signin/faculty': typeof SigninFacultyRoute
  '/signin/students': typeof SigninStudentsRoute
  '/_site/': typeof SiteIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_site/store/$handle': typeof SiteStoreHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/$'
    | '/api/ask'
    | '/api/cart'
    | '/portal/class'
    | '/portal/faculty'
    | '/portal/help'
    | '/portal/library'
    | '/portal/person'
    | '/portal/schedule'
    | '/portal/student'
    | '/portal/writing'
    | '/signin/faculty'
    | '/signin/students'
    | '/portal/'
    | '/store/$handle'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/api/ask'
    | '/api/cart'
    | '/portal/class'
    | '/portal/faculty'
    | '/portal/help'
    | '/portal/library'
    | '/portal/person'
    | '/portal/schedule'
    | '/portal/student'
    | '/portal/writing'
    | '/signin/faculty'
    | '/signin/students'
    | '/'
    | '/portal'
    | '/store/$handle'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_site'
    | '/login'
    | '/portal'
    | '/_site/$'
    | '/api/ask'
    | '/api/cart'
    | '/portal/class'
    | '/portal/faculty'
    | '/portal/help'
    | '/portal/library'
    | '/portal/person'
    | '/portal/schedule'
    | '/portal/student'
    | '/portal/writing'
    | '/signin/faculty'
    | '/signin/students'
    | '/_site/'
    | '/portal/'
    | '/_site/store/$handle'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ApiAskRoute: typeof ApiAskRoute
  ApiCartRoute: typeof ApiCartRoute
  SigninFacultyRoute: typeof SigninFacultyRoute
  SigninStudentsRoute: typeof SigninStudentsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/$': {
      id: '/_site/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SiteSplatRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart': {
      id: '/api/cart'
      path: '/api/cart'
      fullPath: '/api/cart'
      preLoaderRoute: typeof ApiCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/class': {
      id: '/portal/class'
      path: '/class'
      fullPath: '/portal/class'
      preLoaderRoute: typeof PortalClassRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/faculty': {
      id: '/portal/faculty'
      path: '/faculty'
      fullPath: '/portal/faculty'
      preLoaderRoute: typeof PortalFacultyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/help': {
      id: '/portal/help'
      path: '/help'
      fullPath: '/portal/help'
      preLoaderRoute: typeof PortalHelpRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/library': {
      id: '/portal/library'
      path: '/library'
      fullPath: '/portal/library'
      preLoaderRoute: typeof PortalLibraryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/person': {
      id: '/portal/person'
      path: '/person'
      fullPath: '/portal/person'
      preLoaderRoute: typeof PortalPersonRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/schedule': {
      id: '/portal/schedule'
      path: '/schedule'
      fullPath: '/portal/schedule'
      preLoaderRoute: typeof PortalScheduleRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/student': {
      id: '/portal/student'
      path: '/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof PortalStudentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/writing': {
      id: '/portal/writing'
      path: '/writing'
      fullPath: '/portal/writing'
      preLoaderRoute: typeof PortalWritingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/signin/faculty': {
      id: '/signin/faculty'
      path: '/signin/faculty'
      fullPath: '/signin/faculty'
      preLoaderRoute: typeof SigninFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/students': {
      id: '/signin/students'
      path: '/signin/students'
      fullPath: '/signin/students'
      preLoaderRoute: typeof SigninStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/store/$handle': {
      id: '/_site/store/$handle'
      path: '/store/$handle'
      fullPath: '/store/$handle'
      preLoaderRoute: typeof SiteStoreHandleRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteSplatRoute: typeof SiteSplatRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteStoreHandleRoute: typeof SiteStoreHandleRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteSplatRoute: SiteSplatRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteStoreHandleRoute: SiteStoreHandleRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface PortalRouteChildren {
  PortalClassRoute: typeof PortalClassRoute
  PortalFacultyRoute: typeof PortalFacultyRoute
  PortalHelpRoute: typeof PortalHelpRoute
  PortalLibraryRoute: typeof PortalLibraryRoute
  PortalPersonRoute: typeof PortalPersonRoute
  PortalScheduleRoute: typeof PortalScheduleRoute
  PortalStudentRoute: typeof PortalStudentRoute
  PortalWritingRoute: typeof PortalWritingRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalClassRoute: PortalClassRoute,
  PortalFacultyRoute: PortalFacultyRoute,
  PortalHelpRoute: PortalHelpRoute,
  PortalLibraryRoute: PortalLibraryRoute,
  PortalPersonRoute: PortalPersonRoute,
  PortalScheduleRoute: PortalScheduleRoute,
  PortalStudentRoute: PortalStudentRoute,
  PortalWritingRoute: PortalWritingRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ApiAskRoute: ApiAskRoute,
  ApiCartRoute: ApiCartRoute,
  SigninFacultyRoute: SigninFacultyRoute,
  SigninStudentsRoute: SigninStudentsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
